spring.application.name=CsvToJsonExtractor

spring.couchbase.connection-string=127.0.0.1
spring.couchbase.username=Administrator
spring.couchbase.password=Mysql@12345
spring.couchbase.bucket.name=uat_iCache

spring.couchbase.scope.name=customer_master_v6
spring.couchbase.collection.fin_gam.name=fin_gam



successFileName = /successfullyUpdatedData.txt
failedFileName = /failedToUpdateData.txt

logging.file.name=logs/application.log
