spring.application.name=CsvToJsonExtractor

#spring.profiles.active=dev
#spring.couchbase.connection-string=127.0.0.1
#spring.couchbase.username=Administrator
#spring.couchbase.password=Mysql@12345
#spring.couchbase.bucket.name=uat_iCache

spring.profiles.active=uat
spring.couchbase.connection-string=couchbases://cb.66oqs4grwso6sf2w.cloud.couchbase.com
spring.couchbase.username=iCacheUser1
spring.couchbase.password=#iCacheUser@01
spring.couchbase.bucket.name=uat_iCache
#security.enableTls=true

spring.couchbase.scope.name=customer_master_v6
spring.couchbase.collection.fin_gam.name=fin_gam

successFileName = /successfullyUpdatedData.txt
failedFileName = /failedToUpdateData.txt
batchSize = 500
logging.file.name=logs/application.log
csvFileName=/ACIDData_UAT.csv
